volumes:
  kafka_volume:
  es_volume:
services:
  kafka:
    image: 'bitnami/kafka:3.3.1'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.25.0.2:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    volumes:
      - kafka_volume:/bitnami/kafka
    networks:
      - elk

  elasticsearch:
    image: elasticsearch:8.15.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_volume:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: logstash:8.15.3
    container_name: logstash
    ports:
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: kibana:8.15.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://172.25.0.3:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge





